# Numpy

* grande quantidade de dados
* se assemelha a lista mas tem mais "poder"
* numpy é escrito em C
* https://medium.com/ensina-ai/entendendo-a-biblioteca-numpy-4858fde63355
* https://pypi.org/

###### O NumPy é uma poderosa biblioteca Python que é usada principalmente para realizar cálculos em Arrays Multidimensionais. O NumPy fornece um grande conjunto de funções e operações de biblioteca que ajudam os programadores a executar facilmente cálculos numéricos. Esses tipos de cálculos numéricos são amplamente utilizados em tarefas como
* Modelos de Machine Learning
* Processamento de Imagem e Computação Gráfica
* Tarefas matemáticas

** Instalar a biblioteca caso não tennha ** py -m pip install numpy

In [107]:
#como fazer o import
import numpy as np

In [108]:
#lista
v = [10,20,30,40]

In [109]:
#como ver o tipo de uma variável
type(v)

list

In [110]:
type(1.5)

float

In [111]:
#criando o primeiro array com a numpy a partir de uma lista
arr = np.array(v)

In [113]:
#acessando as posições do array
print(arr[-1])
print(arr[0])

40
10


In [114]:
#verificando o tipo da variável
type(arr)

numpy.ndarray

In [115]:
#pegando o maior valor do array
arr.max()

40

In [116]:
#pegando o menor valor do array
arr.min()

10

In [117]:
#criando uma lista de listas similar a uma matriz
lista_lista = [[1,2,3],[22,3,2],[1,2,3]]

In [118]:
#criando uma matriz via num py com mais de uma dimensão
m_numpy = np.array(lista_lista)

In [120]:
#verifica a ordem da matriz ou quantidade de elementos 
#por linha coluna etc
m_numpy.shape

(3, 3)

In [121]:
#visualização
m_numpy

array([[ 1,  2,  3],
       [22,  3,  2],
       [ 1,  2,  3]])

In [122]:
#mudando o valor de um elemento da matriz
m_numpy[-1][-1] = 8

In [123]:
#mudando uma linha inteira da matriz por novos valores
m_numpy[1] = [3,4,5]

In [38]:
#mudando uma linha inteira da matriz 
#por um valor especifico em todos os elementos
m_numpy[0] = 2

In [124]:
#operações com cada elemento da matriz
#são validas qualquer operação aritmética
m_numpy + 98

array([[ 99, 100, 101],
       [101, 102, 103],
       [ 99, 100, 106]])

In [125]:
#criando uma lista ordenada começando em 5 e indo até 9(10-1)
list(range(5,10))

[5, 6, 7, 8, 9]

In [127]:
#criando uma lista ordenada começando em 5 e indo até 9(10-1)
#pulando de 2 em 2
np.arange(5,10,2)

array([5, 7, 9])

In [129]:
#criando uma matriz totalmente de zeros
#ordem de 5 linhas e 3 colunas
np.zeros((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [130]:
#criando uma matriz totalmente de uns
#ordem de 3 linhas e 4 colunas
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [131]:
#criando a matriz identidade
#tem determinante igual a 1 
#diagonal principal com 1
#todo o resto é zero
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [132]:
#mudando a ordem da matriz
np.arange(41*5).reshape(41,5)

array([[  0,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24],
       [ 25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34],
       [ 35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44],
       [ 45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54],
       [ 55,  56,  57,  58,  59],
       [ 60,  61,  62,  63,  64],
       [ 65,  66,  67,  68,  69],
       [ 70,  71,  72,  73,  74],
       [ 75,  76,  77,  78,  79],
       [ 80,  81,  82,  83,  84],
       [ 85,  86,  87,  88,  89],
       [ 90,  91,  92,  93,  94],
       [ 95,  96,  97,  98,  99],
       [100, 101, 102, 103, 104],
       [105, 106, 107, 108, 109],
       [110, 111, 112, 113, 114],
       [115, 116, 117, 118, 119],
       [120, 121, 122, 123, 124],
       [125, 126, 127, 128, 129],
       [130, 131, 132, 133, 134],
       [135, 136, 137, 138, 139],
       [140, 141, 142, 143, 144],
       [145, 1

In [65]:
np.arange(27).reshape(3,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [133]:
#mudando a ordem da matriz e trazendo agora 4 dimensões
np.arange(81).reshape(3,3,3,3)

array([[[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]],

        [[18, 19, 20],
         [21, 22, 23],
         [24, 25, 26]]],


       [[[27, 28, 29],
         [30, 31, 32],
         [33, 34, 35]],

        [[36, 37, 38],
         [39, 40, 41],
         [42, 43, 44]],

        [[45, 46, 47],
         [48, 49, 50],
         [51, 52, 53]]],


       [[[54, 55, 56],
         [57, 58, 59],
         [60, 61, 62]],

        [[63, 64, 65],
         [66, 67, 68],
         [69, 70, 71]],

        [[72, 73, 74],
         [75, 76, 77],
         [78, 79, 80]]]])

In [134]:
#como validar a existência de uma letra dentro de uma string
'a' in 'abc'

True

In [135]:
#como validar a existência de uma letra dentro de uma string
'd' in 'abc'

False

In [68]:
#como validar a existência de um número dentro de uma lista
1 in [1,2,3]

True

In [69]:
#como validar a existência de um número dentro de uma lista
4 in [1,2,3]

False

In [71]:
#como validar a existência de um número dentro de um array ou matriz numpy
11 in np.arange(10)

False

In [73]:
matriz = np.ones((3,3))

In [74]:
matriz

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [77]:
2 in matriz

False

In [78]:
1 in matriz

True

In [136]:
#como validar a existência um número ou string no dicionário
x = {
    'nome': 'Miura'
    ,'idade':26
}

In [80]:
'nome'  in x

True

In [81]:
'Miura' in x

False

In [137]:
#traz apenas as chaves do dicionário
x.keys()

dict_keys(['nome', 'idade'])

In [138]:
#traz apenas os valores dos dicionários
x.values()

dict_values(['Miura', 26])

In [84]:
'nome' in x.keys()

True

In [85]:
26 in x.values()

True

# Resolução do Desafio do Iris.csv

In [139]:
#lendo um arquivo com a numpy
dados = np.genfromtxt('iris.csv',delimiter=';',dtype='object')

In [140]:
#pegando todas as colunas numericas
colunas = dados[:,:-1].astype(float)

In [141]:
#pegando a coluna das especies
especies = dados[:,-1]

In [143]:
#pegando somente 1 nome de cada espécie
grupos_unicos = np.unique(especies)

In [147]:
#laço para cada especie no grupo de especies
for grupo in grupos_unicos:
    #nome da especie
    print(grupo)
    
    #pegando o indice do da matriz que contem aquela especie na linha
    indices = np.where(especies == grupo)[0]
    
    #indices da especie em questão
    print(indices)
    print('-'*60)
    
    #calculo da média para aquelas especies
    media = np.mean(colunas[indices],axis=0)
    
    #print mostrando a média por coluna da especie
    print("Grupo {}: {}".format(grupo, media))
    print('='*60)
    print('\n'*3)

b'setosa'
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]
------------------------------------------------------------
Grupo b'setosa': [25.5    5.006  3.418  1.464  0.244]




b'versicolor'
[50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73
 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97
 98 99]
------------------------------------------------------------
Grupo b'versicolor': [75.5    5.936  2.77   4.26   1.326]




b'virginica'
[100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117
 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135
 136 137 138 139 140 141 142 143 144 145 146 147 148 149]
------------------------------------------------------------
Grupo b'virginica': [125.5     6.588   2.974   5.552   2.026]




