# Exercícios NumPy  

Agora que aprendemos sobre NumPy, vamos testar seu conhecimento. Começaremos com algumas tarefas simples, para depois entrarmos nas perguntas mais complicadas.

#### Importe NumPy como np

In [1]:
import numpy as np

#### Crie uma matriz de 10 zeros

In [2]:
arr = np.zeros(10)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Crie uma matriz de 10 ones

In [3]:
arr = np.ones(10)
arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Crie uma matriz de 10 cincos

In [4]:
arr + 4

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### Crie um array de inteiros de 10 até 50

In [5]:
arr = np.arange(10,50)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### Crie um array dos numeros pares de 10 até 50

In [6]:
arr = np.arange(10,50,2)
arr

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

#### Criei uma matriz 3x3 com valores variando de 0 até 8

In [60]:
#reshape modifica o array para o formado definido no tipo reshape(linha,coluna)
arr =  np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Crie uma matriz identidade 3x3

In [61]:
#cria uma matriz com a diagonal setada
#esta função tbm pode ser usada para obter a diagonal de uma matriz inserida
np.diag([1,1,1])

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

#### Use NumPy para gerar números aleatórios entre 0 e 1

In [62]:
#random.rand() cria um número aleatório entre 0 e 1
np.random.rand()

0.2034381249242425

#### Use Numpy para gerar um array de 25 números aleatórios tirados de uma distribuição normal.

In [63]:
#randn cria uma matriz com valores randomicos
arr = np.random.randn(5,5)
arr

array([[ 1.06982025, -1.43648307, -0.28200338, -2.08974247,  0.81115806],
       [ 1.3649325 ,  0.88290053, -0.80415884,  0.11345827, -0.58107527],
       [-0.30527527,  1.43682839, -0.46463408, -0.33599499, -1.20684027],
       [ 2.77231561, -0.04684038, -0.43121642, -2.1297474 , -1.37176975],
       [ 0.73227245, -1.43339341, -1.08969799,  1.11452279,  0.45318315]])

#### Crie a seguinte matriz:

In [11]:
step = 0.01
arr = np.arange(step,1+step,step).reshape(10,10)

arr

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

#### Crie um array de tamanho 20 igualmente espaçado entre 0 e 1.

In [12]:
step = 1/19
arr = np.arange(0,1+step,step).reshape(5,4)
arr

array([[0.        , 0.05263158, 0.10526316, 0.15789474],
       [0.21052632, 0.26315789, 0.31578947, 0.36842105],
       [0.42105263, 0.47368421, 0.52631579, 0.57894737],
       [0.63157895, 0.68421053, 0.73684211, 0.78947368],
       [0.84210526, 0.89473684, 0.94736842, 1.        ]])

## Indexação Numpy e Seleção

Agora você receberá algumas matrizes e será solicitado a replicar as saídas resultantes da matriz:

In [13]:
arr = np.arange(1,26).reshape(5,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

* ESCREVE O CÓDIGO AQUI QUE REPRODICA A SAÍDA DA CÉLULA ABAIXO
* SEJA CUIDADOSO PARA NÃO FUNCIONAR A CÉLULA ABAIXO, DE OUTRA FORMA, NÃO PODERÁ
* PODE VER A SORTEZA MAIS QUALQUER

In [14]:
#compress escolhe as linhas ou colunas que serão removidas, atravéz de uma lista de booleando compress(lista de booleano,array,axix=linha(0)/coluna(1))
a = np.compress([0,0,1,1,1],arr,axis=0)
b = np.compress([0,1,1,1,1],a,axis=1)
b

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

* ESCREVE O CÓDIGO AQUI QUE REPRODICA A SAÍDA DA CÉLULA ABAIXO
* SEJA CUIDADOSO PARA NÃO FUNCIONAR A CÉLULA ABAIXO, DE OUTRA FORMA, NÃO PODERÁ
* PODE VER A SORTEZA MAIS QUALQUER

In [15]:
arr[3,4]

20

In [16]:
arr[-2,-1]

20

* ESCREVE O CÓDIGO AQUI QUE REPRODICA A SAÍDA DA CÉLULA ABAIXO
* SEJA CUIDADOSO PARA NÃO FUNCIONAR A CÉLULA ABAIXO, DE OUTRA FORMA, NÃO PODERÁ
* PODE VER A SORTEZA MAIS QUALQUER

In [17]:
a = np.compress([1,1,1,0,0],arr,axis=0)
b = np.compress([0,1,0,0,0],a,axis=1)
b

array([[ 2],
       [ 7],
       [12]])

In [18]:
a = np.compress([0,1,0,0,0],arr,axis=1)
b = np.compress([1,1,1,0,0],a,axis=0)
b

array([[ 2],
       [ 7],
       [12]])

* ESCREVE O CÓDIGO AQUI QUE REPRODICA A SAÍDA DA CÉLULA ABAIXO
* SEJA CUIDADOSO PARA NÃO FUNCIONAR A CÉLULA ABAIXO, DE OUTRA FORMA, NÃO PODERÁ
* PODE VER A SORTEZA MAIS QUALQUER

In [19]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [20]:
np.compress([0,0,0,0,1],arr,axis=0)

array([[21, 22, 23, 24, 25]])

* ESCREVE O CÓDIGO AQUI QUE REPRODICA A SAÍDA DA CÉLULA ABAIXO
* SEJA CUIDADOSO PARA NÃO FUNCIONAR A CÉLULA ABAIXO, DE OUTRA FORMA, NÃO PODERÁ
* PODE VER A SORTEZA MAIS QUALQUER

In [21]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [22]:
np.compress([0,0,0,1,1],arr,axis=0)

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Agora faça o seguinte

#### Obter a soma de todos os valores no "mat"

In [25]:
#somma todas as linhas, e dopois soma a linha resultante
sum(sum(arr))

325

In [53]:
#esta função cria um array que que é soma todos elementos da matriz de um a um, o ultimo elemento do array é a soma de todos elementos da matris
np.cumsum(arr)[24]

325

#### Obter o desvio padrão dos valores em mat

In [43]:
#função que calcula o desvio padrão
np.std(arr)

7.211102550927978

#### Obter a soma de todas as colunas em mat

In [44]:
sum(arr)

array([55, 60, 65, 70, 75])

In [50]:
np.cumsum(arr,axis=0).compress([0,0,0,0,1],axis=0)

array([[55, 60, 65, 70, 75]], dtype=int32)